import React, { useState } from 'react';
import {
  User,
  Cpu,
  Sparkles,
  Globe,
  Share2,
  Download,
  Check,
  ShieldCheck,
  Zap,
  Code2,
  ExternalLink,
  ChevronRight,
  TrendingUp,
  Atom
} from 'lucide-react';
import { IpAnalysisResult } from '../types';

interface ProfileLabViewProps {
  currentProject: IpAnalysisResult;
  hasApiKey: boolean;
}

export const ProfileLabView: React.FC<ProfileLabViewProps> = ({
  currentProject,
  hasApiKey
}) => {
  const [copied, setCopied] = useState(false);
  const [quantumSimulated, setQuantumSimulated] = useState(false);
  const [quantumLoading, setQuantumLoading] = useState(false);

  const handleExportMarkdown = () => {
    const mdContent = `# IP CrossLab 跨媒體 IP 深度策劃白皮書
**專案名稱**：${currentProject.query}
**評估日期**：${currentProject.createdAt}
**目標市場**：${currentProject.targetMarket}
**IP 綜合評分**：${currentProject.overallScore} / 100

---

## 1. 核心評估觀點
> "${currentProject.oneLinerVerdict}"

## 2. 五維潛力拆解
- 🎮 遊戲潛力：${currentProject.potentials.game.score}分 - ${currentProject.potentials.game.analysis}
- 🎬 電影／影集潛力：${currentProject.potentials.movie.score}分 - ${currentProject.potentials.movie.analysis}
- 📺 YouTube 潛力：${currentProject.potentials.youtube.score}分 - ${currentProject.potentials.youtube.analysis}
- 📚 小說／漫畫潛力：${currentProject.potentials.novel.score}分 - ${currentProject.potentials.novel.analysis}
- 💰 商業化潛力：${currentProject.potentials.commercial.score}分 - ${currentProject.potentials.commercial.analysis}

## 3. 五大跨媒體企劃摘要
1. **${currentProject.directions.movie.title}** (${currentProject.directions.movie.badge})
   - Logline: ${currentProject.directions.movie.logline}
2. **${currentProject.directions.game.title}** (${currentProject.directions.game.badge})
   - Game Concept: ${currentProject.directions.game.gameConcept}
3. **${currentProject.directions.youtube.title}** (${currentProject.directions.youtube.badge})
   - 首集標題: ${currentProject.directions.youtube.firstVideoTitle}
4. **${currentProject.directions.novel.title}** (${currentProject.directions.novel.badge})
   - 大綱: ${currentProject.directions.novel.synopsis}
5. **${currentProject.directions.commercial.title}** (${currentProject.directions.commercial.badge})
   - 目標市場: ${currentProject.directions.commercial.targetMarket}

## 4. 推薦推進路線 (Roadmap)
${currentProject.recommendedRoadmap.map((r) => `- **${r.phase}** [${r.timeline}]: ${r.media} (${r.action})`).join('\n')}

---
*Generated by IP CrossLab - AI-Powered Transmedia IP Incubator*`;

    navigator.clipboard.writeText(mdContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2200);
  };

  const handleSimulateQuantum = () => {
    setQuantumLoading(true);
    setTimeout(() => {
      setQuantumLoading(false);
      setQuantumSimulated(true);
    }, 1200);
  };

  return (
    <div className="px-4 py-4 space-y-5">
      {/* Profile Header */}
      <div className="flex items-center gap-3 p-4 rounded-3xl bg-slate-950/80 border border-slate-800 shadow-md">
        <div className="w-12 h-12 rounded-2xl bg-gradient-to-tr from-cyan-500 via-indigo-500 to-fuchsia-500 p-0.5 flex items-center justify-center shrink-0">
          <div className="w-full h-full bg-slate-950 rounded-[14px] flex items-center justify-center">
            <Atom className="w-6 h-6 text-cyan-400" />
          </div>
        </div>
        <div className="min-w-0 flex-1">
          <h2 className="text-sm font-black text-white truncate">
            IP CrossLab 跨媒體實驗室
          </h2>
          <p className="text-[11px] text-slate-400">
            創作者、編劇、遊戲企劃與品牌團隊專用
          </p>
          <div className="flex items-center gap-2 mt-1">
            <span className="text-[9px] px-2 py-0.5 rounded-full bg-cyan-950 text-cyan-400 border border-cyan-800/60 font-semibold">
              Hackathon Edition v1.2
            </span>
            <span className="text-[9px] text-emerald-400 flex items-center gap-1">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
              {hasApiKey ? 'Gemini 3.8 Flash 連線中' : 'Demo 模式運作中'}
            </span>
          </div>
        </div>
      </div>

      {/* Export Report Action Card */}
      <div className="p-4 rounded-3xl bg-gradient-to-r from-cyan-950/40 to-slate-950 border border-cyan-800/40 space-y-3">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="text-xs font-black text-white">
              匯出當前 IP 完整白皮書
            </h3>
            <p className="text-[11px] text-slate-400">
              包含 5 大媒體企劃、三幕劇、玩法循環與商業路線
            </p>
          </div>
          <button
            onClick={handleExportMarkdown}
            className="px-3 py-1.5 rounded-xl bg-cyan-500 hover:bg-cyan-400 active:scale-95 text-slate-950 font-bold text-xs flex items-center gap-1.5 shadow-md transition-all"
          >
            {copied ? <Check className="w-3.5 h-3.5" /> : <Download className="w-3.5 h-3.5" />}
            <span>{copied ? '已複製 Markdown' : '匯出企劃書'}</span>
          </button>
        </div>
      </div>

      {/* Future Expansion: IBM Quantum Optimization Feature Simulation */}
      <div className="p-4 rounded-3xl bg-slate-950/80 border border-indigo-900/40 space-y-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-indigo-500/20 text-indigo-400 flex items-center justify-center">
              <Cpu className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-xs font-black text-white flex items-center gap-1.5">
                IBM Quantum IP Portfolio Optimization
                <span className="text-[9px] px-1.5 py-0.2 rounded bg-indigo-950 text-indigo-400 border border-indigo-800">
                  實驗功能
                </span>
              </h3>
              <p className="text-[10px] text-slate-400">
                以量子退火演算法優化跨媒體預算與投資組合回報率 (QUBO)
              </p>
            </div>
          </div>
        </div>

        {!quantumSimulated ? (
          <button
            onClick={handleSimulateQuantum}
            disabled={quantumLoading}
            className="w-full py-2.5 rounded-xl bg-indigo-600/20 hover:bg-indigo-600/30 border border-indigo-500/40 text-indigo-300 text-xs font-bold transition-all flex items-center justify-center gap-1.5"
          >
            {quantumLoading ? (
              <>
                <div className="w-3.5 h-3.5 border-2 border-indigo-400 border-t-transparent rounded-full animate-spin" />
                <span>正在模擬量子比特退火運算...</span>
              </>
            ) : (
              <>
                <Zap className="w-3.5 h-3.5 text-indigo-400" />
                <span>執行量子退火跨媒體預算最佳化試算</span>
              </>
            )}
          </button>
        ) : (
          <div className="p-3 rounded-2xl bg-indigo-950/40 border border-indigo-700/50 space-y-2 text-xs">
            <div className="flex items-center justify-between text-indigo-300 font-bold">
              <span>⚛️ 量子退火最優配置結果</span>
              <span className="text-[10px] text-emerald-400 font-mono">ROI 預期 +34.2%</span>
            </div>
            <div className="grid grid-cols-2 gap-1.5 text-[11px] text-slate-300">
              <div className="p-1.5 bg-slate-900/60 rounded">1. 宣傳期 YouTube 投入 18%</div>
              <div className="p-1.5 bg-slate-900/60 rounded">2. 條漫驗證投入 12%</div>
              <div className="p-1.5 bg-slate-900/60 rounded">3. 遊戲 Demo 開發 45%</div>
              <div className="p-1.5 bg-slate-900/60 rounded">4. 影視提案儲備 25%</div>
            </div>
            <p className="text-[10px] text-slate-400 italic">
              量子計算模型已收斂至全域最低風險能量基態，最大化防禦跨媒體授權邊界稀釋。
            </p>
          </div>
        )}
      </div>

      {/* Future Roadmap Pipeline Preview */}
      <div className="space-y-2">
        <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wide">
          未來功能路線圖 (Roadmap & Ecosystem)
        </h3>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
          {[
            { title: 'AI 角色生成與三視圖', status: 'Next Sprint', desc: '為遊戲與影視自動輸出角色 Prompt 與概念設定' },
            { title: 'AI 分鏡腳本與動態預覽', status: 'Next Sprint', desc: '串接生圖模型自動生成電影分鏡與 YouTube 縮圖' },
            { title: '多語言海外拓銷 (日/英/韓)', status: 'Planned', desc: '一鍵轉譯多國文化在地化宣傳文案' },
            { title: '影視製作與發行媒合通道', status: 'Ecosystem', desc: '直接媒合 OTT 串流平台、遊戲發行商與授權買家' },
          ].map((item, idx) => (
            <div key={idx} className="p-3 rounded-2xl bg-slate-950 border border-slate-800 space-y-1">
              <div className="flex items-center justify-between">
                <span className="font-bold text-white text-xs">{item.title}</span>
                <span className="text-[9px] px-1.5 py-0.5 rounded bg-slate-800 text-slate-400">
                  {item.status}
                </span>
              </div>
              <p className="text-[11px] text-slate-400">{item.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
